### ISSUE TITLE
Backward mapping

### ISSUE THREAD

**Issue by Nathan-zh** [ISYSLAB-HUST/ProtFlash#3]
Hi,

After I do some perturbation on the feature space, is it possible to map the features back to amino acid sequence? Thanks!

**Comment by wangleiofficial** [comment]
Hi, I haven't tested this strategy, if you need help, I'll do my best to provide it.

**Comment by Nathan-zh** [comment]
Thanks, currently I'm using VAE to encode the sequence and it works well. If I need some professional encoders like yours, I'll ask for your help.
